/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lingxiao_thefirst_mine_ndk_HelloJni */

#ifndef _Included_com_lingxiao_thefirst_mine_ndk_HelloJni
#define _Included_com_lingxiao_thefirst_mine_ndk_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lingxiao_thefirst_mine_ndk_HelloJni
 * Method:    getCString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lingxiao_thefirst_mine_ndk_HelloJni_getCString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
